### ISSUE TITLE
Need to work on APK smali File

### ISSUE THREAD

**Issue by arunjain2085** [infahash/antiguard#1]
Hello Please Tell if you can work on smali i have an project to work thanks

**Comment by infahash** [comment]
Sorry. No time to spend on new projects.

**Comment by andyenglysh** [comment]
HELLLO

**Comment by andyenglysh** [comment]
NEED TO EDIT MY APK PLEASE

**Comment by brunoaduarte** [comment]
Hi @infahash , how are you?

Need some help decompiling and recompiling latest version of WhatsApp... I'm willing to pay for it.

Can you help me?
